binux/pyspider

docs/Command-Line.md
Should be true rather than ture
=> Fix spelling error

pyspider/database/__init__.py, pyspider/database/mysql/projectdb.py, pyspider/database/mysql/resultdb.py, pyspider/database/mysql/taskdb.py, pyspider/scheduler/scheduler.py, pyspider/webui/index.py, pyspider/webui/templates/result.html
Changed default to InnoDB and results column to MEDIUMBLOB and fixed truncate in the result template in WebUI.
truncate(100) isnt always working properly [:100] works better and is easier.
=> Changed default to InnoDB and results column to MEDIUMBLOB and fixed truncate in the result template in WebUI.

.travis.yml, pyspider/libs/beanstalk.py, tests/test_message_queue.py, tests/test_scheduler.py
Fix bug which caused lock when use a beanstalk queue.
=> Fix deadlocked when use beanstalk

docs/tutorial/HTML-and-CSS-Selector.md
Just as the last issue, seems the file structure changed. To be honest, this is my first Propose file change, and I don't know whether the correction is right or not. Just hope can help a little.
=> correct image links in tutorial

docs/apis/self.crawl.md
don't -> doesn't
import son -> import json
=> fix code and grammer

pyspider/webui/login.py
Fix https://github.com/binux/pyspider/issues/280
Provide a AnonymousUser class and set the  `anonymous_user` in login_manager.
=> Fix issue-280

pyspider/libs/utils.py, pyspider/message_queue/beanstalk.py
=> pretty_unicode not return str for python3 in some case

pyspider/fetcher/tornado_fetcher.py, pyspider/libs/base_queue.py, pyspider/libs/bench.py, pyspider/libs/queue.py, pyspider/message_queue/__init__.py, pyspider/message_queue/beanstalk.py, pyspider/message_queue/kombu_queue.py, pyspider/message_queue/rabbitmq.py, pyspider/message_queue/redis_queue.py, pyspider/processor/processor.py, pyspider/result/result_worker.py, pyspider/scheduler/scheduler.py, pyspider/scheduler/task_queue.py, pyspider/webui/index.py, tests/test_fetcher.py, tests/test_fetcher_processor.py, tests/test_processor.py, tests/test_result_worker.py, tests/test_scheduler.py
So pyspider's dashboard works on Mac now.
=> fix Queue.qsize NotImplementedError on Mac OS X

pyspider/fetcher/phantomjs_fetcher.js
Code from http://stackoverflow.com/a/16709386/150841, thanks PP.
=> Enable console.log in PhantomJS

pyspider/libs/utils.py
fix unicode_dict: unicode_string --> unicode_obj
=> fix bug for unicode_dict

pyspider/webui/index.py
Sort project by name make it more easy to find a project on webui when one set project name like `game_gamesky` , `game_tgbus`
=> sort project by name on webui index

Dockerfile
Update Dockerfile about new version mysql connector
=> Update Dockerfile about new version mysql connector

pyspider/libs/base_handler.py
Sometimes the processor hangs and cause the whole crawling system stop working. I think adding `process_time_limit` to the functions can help us for better debugging.
I add `process_time_limit` to `BaseHandler.process_fields` and use `pyspider.libs.utils.timeout` in `BaseHandler._run_func`.
Then such function can raise an `TimeoutError` when it takes a long time to process.
```
@config(age=10 * 24 * 60 * 60, process_time_limit=3)
def index_page(self, response):
time.sleep(2)
for each in response.doc('a[href^="http"]').items():
self.crawl(each.attr.href, callback=self.detail_page)
```
=> add processing time limit

pyspider/webui/templates/result.html
This page will get an InternalError if there's not any result.Because line:70 the variable count is None.
=> Error in pyspider dashboard when there's nothing in project results.

docs/Frequently-Asked-Questions.md
vim dav://hostname/dav/script_name.py  does not work,  change the "dav" to "http", it works well :)
=> change the path of webdav edit file

pyspider/database/sqlalchemy/projectdb.py
=> add project db primary key

pyspider/database/base/projectdb.py, pyspider/database/base/taskdb.py, pyspider/database/basedb.py, pyspider/database/elasticsearch/projectdb.py, pyspider/database/elasticsearch/taskdb.py, pyspider/database/mongodb/projectdb.py, pyspider/database/mongodb/taskdb.py, pyspider/database/mysql/projectdb.py, pyspider/database/mysql/taskdb.py, pyspider/database/redis/taskdb.py, pyspider/database/sqlalchemy/projectdb.py, pyspider/database/sqlalchemy/taskdb.py, pyspider/database/sqlite/projectdb.py, pyspider/database/sqlite/taskdb.py, pyspider/fetcher/cookie_utils.py, pyspider/libs/counter.py, pyspider/libs/response.py, pyspider/libs/url.py, pyspider/libs/wsgi_xmlrpc.py, pyspider/message_queue/__init__.py, pyspider/message_queue/kombu_queue.py, pyspider/message_queue/redis_queue.py, pyspider/processor/processor.py, pyspider/processor/project_module.py, pyspider/webui/task.py, pyspider/webui/webdav.py
解决使用 **pycharm**打开后提示的各种可能的bug。
=> fix some hidden bugs.

pyspider/libs/counter.py
Hello, problem with counter was not totally fixed, here it is same changes as you did before.
=> Add fix for counters

README.md
Some basic changes on the readme.
=> Grammar Changes - Readme

Dockerfile, pyspider/fetcher/puppeteer_fetcher.js, pyspider/fetcher/tornado_fetcher.py, pyspider/run.py
Replenishment and completion #850 and have tested in local development environment.
=> add puppeteer fetcher
