binux/pyspider

docs/Command-Line.md
pyspider/database/__init__.py

When trying to use a custom db config following the document. Newbee like me may get confused when hitting **Exception("unknow database type: type)**.
So I added a hint message.

Add hint for database type config

---

pyspider/database/sqlalchemy/projectdb.py
pyspider/database/sqlalchemy/resultdb.py
pyspider/database/sqlalchemy/taskdb.py

Float(16) if not precise enough for storing unix timestamp, this may cause various bugs.
See my script for testing:
```python
import time
from sqlalchemy import create_engine
from sqlalchemy import Column, Float, MetaData, Table
echo = False
engines = (
('postgresql', create_engine('postgresql://DB_CONFIG', echo=echo)),
('mysql', create_engine('mysql://DB_CONFIG', echo=echo)),
('sqlite', create_engine('sqlite://', echo=echo)),
)
meta_data = MetaData()
test = Table(
'test', meta_data,
Column('col16', Float(precision=16)),
Column('col32', Float(precision=32)),
)
for engine_type, engine in engines:
print 'Engine:', engine_type
meta_data.drop_all(engine)
meta_data.create_all(engine)
now = time.time()
print 'Now:', now
engine.execute('insert into test values (%s, %s)' % (now, now))
for each in …
```

Fix bug: Precision for Float column which stores timestamp is too small

---

pyspider/run.py

I used to run pyspider by running ./run.py
Add this can be easy for the one who use to run it like me

Enable set AMQLURL and PPROXY via env

---

pyspider/libs/beanstalk.py
pyspider/run.py

The default max job size in beanstalkd is 2^16, if you want to use beanstalkd as queue, you need to set param `max-job-size` larger.
setting for beanstalkd
`"DAEMON_OPTS="-l $BEANSTALKD_LISTEN_ADDR -p $BEANSTALKD_LISTEN_PORT -z 524288""`
setting for pyspider in config.json
`"beanstalk": "localhost:11300",`

add queue beanstalk

---

docs/tutorial/index.md

links in http://docs.pyspider.org/en/latest/tutorial/ doesn't work. Seems like file structure changed, so I update the links here

correct links in tutorial

---

pyspider/database/mongodb/resultdb.py
pyspider/webui/result.py

error occurs when I dump resultdb, my env: win8  pymongo (2.8.1)
```
[I 150819 09:00:15 _internal:87] 127.0.0.1 - - [19/Aug/2015 09:00:15] "GET /results/dump/baidu.json HTTP/1.1" 500 -
[E 150819 09:00:15 _internal:87] Error on request:
Traceback (most recent call last):
File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 180, in run_wsgi
execute(self.server.app)
File "C:\Python27\lib\site-packages\werkzeug\serving.py", line 170, in execute
for data in application_iter:
File "C:\Python27\lib\site-packages\werkzeug\wsgi.py", line 693, in __next__
return self._next()
File "C:\Python27\lib\site-packages\werkzeug\wrappers.py", line 81, in _iter_encoded
for item in iterable:
File "C:\Python27\lib\site-packages\pyspider-0.3.6-py2.7.egg\pyspider\libs\result_dump.py", line 50, in …
```

fix dump error while using pymongo

---

docs/apis/self.crawl.md

fix bug for get_taskid when using post in markdown,
'data' is in task['fetch'] but not in task

fix bug for get_taskid when using post in markdown

---

pyspider/message_queue/__init__.py
pyspider/message_queue/redis_queue.py

Now, we can use `redis://:passwd@localhost:6379/0` to connect a redis instance that need password.

add the missing password  parameter for redis message queue

---

docs/apis/self.crawl.md

In scheduler.py
```python
default_schedule = {
'priority': 0,
'retries': 3,
'exetime': 0,
'age': -1,
'itag': None,
}
```
default `age` value is -1.   
and in `on_old_request`  
```python
elif schedule_age >= 0 and schedule_age + (old_task.get('lastcrawltime', 0) or 0) < now:
restart = True
```
age=0 means always recrawl. 
The document  says,
> age - the term of validity of the task. The page would be regarded as not modified during the term. default: 0(never recrawl)  
that is wrong.

fix the wrong age default value in docs

---

pyspider/database/mongodb/resultdb.py
pyspider/database/mongodb/taskdb.py

It would speed scheduler/result_worker up very much by adding taskid index as default.
Without creating index default, I have to excute below js everytime when one add a new project:
```
use 'taskdb';
var collectionNames = db.getCollectionNames();
for (var i=0; i< collectionNames.length; i++ ) {
db.getCollection(collectionNames[i]).ensureIndex( { taskid : 1 } );
}
```

mongodb add taskid index to taskdb and resultdb

---

pyspider/webui/webdav.py

1.`os.path.normpath(path)` would convert `/` to `\\` on windows.
2.`windows map network driver` would access with path  `.`, 
but there is : `assert path=="" or path.startswith("/")` check in wsgidav. 
So `path = '/' if path in ('/', '.', '')`

fix webdav on windows

---

docs/Quickstart.md

include 2 packages `libssl-dev` (**pycurl** required) and `zlib1g-dev` (**lxml** required)

include 2 extra packages required on ubuntu

---

pyspider/database/sqlalchemy/projectdb.py
pyspider/database/sqlalchemy/resultdb.py
pyspider/database/sqlalchemy/taskdb.py

while use mysql+sqlalchemy, if the system idle more than 8 hours, will raise Exception
```
sqlalchemy.exc.OperationalError: (mysql.connector.errors.OperationalError) MySQL Connection not available. [SQL: 'SELECT projectdb.name, projectdb.`group` \nFROM projectdb \nWHERE projectdb.name = %(name_1)s \n LIMIT %(param_1)s']
```
use  `pool_recycle` while `creat_engine` to resolve the problem

Update Database classes in sqlalchemy to use 'pool_recycle'

---

setup.py

1.  `webui/static/src` would be considered as a file and cause install error, so limit to *.css and *.js files.
2.  add missing `fetcher/splash_fetcher.lua`

fix install error

---

pyspider/webui/debug.py
pyspider/webui/index.py

fix "pyspider/webui/index.py:12: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead"

---

requirements.txt

https://github.com/binux/pyspider/blob/master/pyspider/libs/response.py#L15

tblib is required  for pyspider/libs/response.py#L15

---

pyspider/webui/static/src/debug.js

The variable `current_path` needs to be set when selecting an element.

Fix add CSS selector to editor

---

pyspider/database/base/projectdb.py

the origin statement is:
def split_group(self, group, lower=True):
return re.split("\W+", (group or '').lower())
and i wonder whether to add an if statement  or not?

add a flow control statement in projectdb.py

---

pyspider/scheduler/scheduler.py

In some rare occasions, some users may use some "illegal" float values for their cron_job function. For example,
```
@every(seconds=0.1)
def on_start(self):
...
```
Then the `project.min_tick` will be `0.1` which will lead to a `ZeroDivisionError` when scheduler is doing `_check_cronjob` ([Line 429 of `scheduler.py`](https://github.com/binux/pyspider/blob/master/pyspider/scheduler/scheduler.py#L429)):
```
...
if self._last_tick % int(project.min_tick) != 0:
continue
...
```

ZeroDivisionError when int(min_tick) == 0

---

pyspider/fetcher/phantomjs_fetcher.js
pyspider/libs/base_handler.py

Tried to make things right this time.

add phantomjs proxy support

---

docs/Command-Line.md
docs/Deployment.md
pyspider/message_queue/__init__.py
pyspider/message_queue/redis_queue.py
requirements.txt
setup.py

The default redis package is not supported in the cluster mode. So ... it may helps for who deploy pyspider with redis cluster.
It has been tested and works well in production environment with redis 3.x of **cluster** mode.
Then the config template can be 
```
redis:
redis://host:6379/db
or
redis://host1:port1,host2:port2,...,hostn:portn (for redis 3.x in cluster mode)
```
ex. (3 master & 3 slave as my development environment )
```
url='redis://10.78.155.61:16340,10.78.155.67:16340,10.78.155.68:16340,10.78.155.70:16340,10.78.155.71:16340,10.78.155.72:16340'
```

support redis 3.x in cluster mode for message queue

---

.gitignore
pyspider/database/mongodb/resultdb.py
pyspider/database/mongodb/taskdb.py

>  当result、task 表数据量较大时，启动后建索引会等待很长时间，尤其是分布式部署情况下，每个进程启动后都会重建索引
> aggregate做分组统计时进行全表扫描，比较慢，实际项目种导致scheduler模块启动时长接近30min，
> 考虑到status字段有索引，直接进行count统计反而效果比较好
> 实测效果优于aggregate操作

mongodb操作优化

---

pyspider/database/sqlalchemy/resultdb.py

It looks like creation of resultdb is not same as creation of projectdb and taskdb. This may cause error for postgres in Python3

Fixed db inconsistency

---

pyspider/scheduler/scheduler.py
pyspider/scheduler/task_queue.py
tests/test_scheduler.py
tests/test_task_queue.py

- Dynamic calculate select limit for each project when doing _check_select;
- Improve task queue, keep tasks( with the same priority ) in time order when use heap sort.
- In my project, this heap queue behaves more like a FILO stack when the speed of request faster than select, and this case big problem.

optimise scheluler dynamic select limit and improve task queue

---

pyspider/fetcher/tornado_fetcher.py
pyspider/run.py
tests/test_fetcher_processor.py
tests/test_response.py

async and await are now reserved keywords in python3.7, so async can not be used as function args' key.

change async to async_

---

.travis.yml

Thought I would try updating the travis ci file a bit so that some of the versions pass to let the travis builds pass overall. Looking into the pycparser build issue with 2.6 I found the guy had dropped support for pre 2.7 versions so I think it should be dropped from travis. 
The next bit with 3.5 I'm not entirely sure on so feel free tell me if I'm messing something up. The build for 3.5 fails on the --no-use-wheel also fails on --allow-all-external after that. I think pip had dropped them after version 10. For some reason 3.5 has pip version 18 so I changed the pip install lines to avoid the errors with the parameters being gone. It's build passes with them gone so I think it's okay?

Proposed changes to travis ci file to allow passing builds
